### PR TITLE
Update MODULES.yml

### PR DESCRIPTION
**Pull request by hereariim**
Here my deepaas module

### CODE REVIEW

**Comment by IgnacioHeredia** [comment]
Hi @hereariim, please change the [title](https://github.com/hereariim/DEEP-OC-blossom/blob/a5dcfb6ffea5fba45f1940acfed68779ff1d9d00/metadata.json#L2) to something more specific:
```json
    "title": "Apple tree blossom segmenter",
```

**Comment by hereariim** [comment]
thank you, yes i just added a title

**Comment by IgnacioHeredia** [comment]
@hereariim , you should also fix [this line](https://github.com/hereariim/DEEP-OC-blossom/blob/6d7407fd780b2a64280919c79d5740b9cef213d4/metadata.json#L18):
```json
		"docker_registry_repo": "deephdc/deep-oc-blossom",
```

**Comment by hereariim** [comment]
thank you, I replaced "herearii/deep-oc-blossom" to "deephdc/deep-oc-blossom"

**Pull request merged**
